### ISSUE TITLE
Cannot assign key shortcut

### ISSUE THREAD

**Issue by Dolland** [velitasali/gnome-shell-extension-awesome-tiles#1]
As per title, i cannot change shortcut from "extensions" app, menu remains on "press your keyboard shortcut..."

GNOME 40
Ubuntu 21.10

**Comment by velitasali** [comment]
Which key combinations are you trying? It should be a valid combination for the extension to register your input.

**Comment by Dolland** [comment]
Basically every combination:
Super + any key
Ctrl + any key

What can be "valid combinations"?

**Comment by velitasali** [comment]
Yes, I have found the issue. I will release a new update. Thanks for reporting this!

**Comment by Dolland** [comment]
Can't wait to new release, i'm desperately searching for a tool that make exactly what your extension does

**Comment by velitasali** [comment]
I am glad to hear that. I have enabled the Discussions tab in case you have suggestions :)

**Comment by Dolland** [comment]
I'd like to use arrows to move windows, are arrows valid keys? 
BTW it may be comfortable to put a set of "unvalid" keys on readme :)

**Comment by velitasali** [comment]
By invalid combinations, I mean things like a key with no modifier such as `k`. That wouldn't work obviously. I didn't know I forgot an import that caused this bug :)

About arrow, I think they would work, but GNOME Shell already makes use of them, so I would try some other keybindings.

Btw, the commit above should fix the issue. You can clone the repo and install the extension by following the instructions that can be found in the README.

**Comment by Dolland** [comment]
yep, last commit fixed the bug!
It may be usefull also to erase keybinding, it seems it isn't possible

**Comment by velitasali** [comment]
Yes, I have considered it but let it slide for the first release. I will think about it for the coming releases. Thanks for the suggestion :)

**Comment by iMonZ** [comment]
Still same issue :(
Ubuntu 21.10

**Comment by velitasali** [comment]
@iMonZ It doesn't assign keys?

**Comment by spacesofspace** [comment]
Hi,

I hope all's well.

Still, I cannot assign key shortcuts.

Ubuntu 23.04
GNOME Shell 44.1

Any ideas on how to resolve?

Thanks,
d.
