### ISSUE TITLE
Disable shortcut

### ISSUE THREAD

**Issue by joseph-zhong** [velitasali/gnome-shell-extension-awesome-tiles#13]
Hi, thanks for this awesome plugin -- been using for the past few days and really loving it, especially the extremely intuitive "press-again" to increase/decrease the size!

One question I had was: is it possible to add a simple "Disable shortcut" feature?
The default shortcuts implements this nicely by just setting "press ESC to cancel, ENTER to confirm, and BACKSPACE to disable"

I'll sometimes accidentally click a setting, and I'm forced to assign a shortcut that doesn't interfere, and I'd assume it's basically safe to assume that "ESC", "BACKSPACE" and "ENTER" should be safe to never be part of the shortcut commands

**Comment by velitasali** [comment]
Hi! I implemented this in the referenced commit above.
