### ISSUE TITLE
settings menu doesn't open on 20.04

### ISSUE THREAD

**Issue by Dahaniel** [velitasali/gnome-shell-extension-awesome-tiles#15]
Hey there, firstly thanks for that great extension!

Unfortunately on 20.04 (tested on 2 PCs) the settings window does not open. Extension version is 4.

Otherwise its working fine but on the laptiop I need to change the shortcuts as I don't have a numpad.

**Comment by velitasali** [comment]
Hi, @Dahaniel,

[Here](https://www.gnome.org/getting-gnome/#:~:text=Ubuntu%2020.04%20LTS%20includes%20GNOME%203.36%20with%20minor%20alterations%20and%20Ubuntu%2021.10%20includes%20GNOME%2040%2C%20also%20with%20minor%20alternations.%20If%20you%20install%20gnome%2Dsession%2C%20you%20can%20also%20choose%20to%20launch%20a%20pristine%20GNOME%20from%20the%20login%20screen.) it says Ubuntu 20.04 has GNOME 3.36 in its repos, which this extension doesn't support. Unless you're using GNOME 40+ with PPAs or something, backporting  the preferences UI of the extension to GTK3 is needed.

**Comment by Dahaniel** [comment]
@velitasali thanks for the info, its time for me to upgrade to 22.04 then I guess.

**Comment by nkrot** [comment]
information about minimal required version should be displayed in README.md
