### ISSUE TITLE
[Suggestion] Allow multiple sizes with tile window to center

### ISSUE THREAD

**Issue by ThomasLobker** [velitasali/gnome-shell-extension-awesome-tiles#18]
Using the _**Tile window to center**_ keyboard shortcut you will end up with a large centralized window. And on an ultrawide monitor you will end up with a _huge_ centralized window. It would be nice if you could press the keyboard shortcut several times and go through multiple sizes. Just like you go through three different sizes while tiling left or right.

Thanks and keep up the good work!

**Comment by lonix1** [comment]
Agreed!

That is the only feature I miss from ["Put Windows"](https://github.com/negesti/gnome-shell-extensions-negesti). When one presses super+5, it will maximise, then show the window at "normal" size, then an intermediate size.

**Comment by lonix1** [comment]
@thomas Also see https://github.com/velitasali/gnome-shell-extension-awesome-tiles/issues/25

**Comment by nushoin** [comment]
I believe that this issue can be closed as #22 was merged back in August.

@velitasali is the extension on https://extensions.gnome.org/extension/4702/awesome-tiles/ up to date? Maybe people are unaware of the fix.

**Comment by ThomasLobker** [comment]
> I believe that this issue can be closed as #22 was merged back in August.

Much appreciated! I was unaware of the fix. Though this is a great improvement it's still not perfect on an ultra-wide monitor. It would be nice to be able and configure the width and height of each cycle, perhaps in a future update.

Thanks and great work :+1:
