### ISSUE TITLE
gap between window switch does not work

### ISSUE THREAD

**Issue by fastrizwaan** [velitasali/gnome-shell-extension-awesome-tiles#19]
![image](https://user-images.githubusercontent.com/1161682/182148761-10fb3398-e228-4d5e-8c75-2dcb2c79db7e.png)

The toggle switch is not working. I had to manually set gap to 0 to make it work like above.

Gnome 42.3.1
Debian (bookworm)
Nvidia drivers

**Comment by velitasali** [comment]
I am not sure what you mean by _not working_. Do you mean the toggle doesn't work ever? Or does it not have the expected effect?

For reference, the toggle sets whether there should be gaps _between windows_. If you want to disable the gaps _around windows_, then yes, setting the value of the spin button to 0 is what you should do.

**Toggle enabled**

![Screenshot from 2022-08-01 15-43-56](https://user-images.githubusercontent.com/10258162/182151064-449cf981-df46-400b-aaeb-230391b07af3.png)

**Toggle disabled**

![Screenshot from 2022-08-01 15-43-25](https://user-images.githubusercontent.com/10258162/182151196-adf44d2d-15bc-4036-aa23-72424b8378d5.png)

**Comment by fastrizwaan** [comment]
Oh, sorry, Gap between workspace and windows are different.  

NOT A BUG
