### ISSUE TITLE
Tiling Bottom Edge does not reach monitor edge on Vertical Orientation

### ISSUE THREAD

**Issue by Chake96** [velitasali/gnome-shell-extension-awesome-tiles#34]
Currently, when you have a vertically oriented monitor and try to tile a window either in the center or to the bottom it does not align to the window edge. There is a small gap and I think its from not including the height of the window's title bar in the _tileWindow function. I've implemented a fix Im happy to create a MR for.

**Comment by velitasali** [comment]
Hi, @Chake96. 

Yes, of course! Please feel free to open a pull request.
