### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by FiestaLake** [velitasali/gnome-shell-extension-awesome-tiles#45]
Would you mind adding support for gnome-45?

**Comment by titaniumbones** [comment]
I believe it's a bit more involved than it has been in other recent releases: 
https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/ 

I don't think it's incredibly difficult, but I haven't written JavaScript for a while and when I did do these conversions, it was always a bit more fiddly than I expected.  

If someone does manage to modify the code, it'd be fantastic if you posted the branch here so the rest of us cna pull.

**Comment by velitasali** [comment]
Hi! I started working on this. The extension now works, but the preferences window needs to be ported to `AdwPreferencesPage`.  I will finish that in a few days. Thank you!

![Screenshot from 2023-10-18 12-20-27](https://github.com/velitasali/gnome-shell-extension-awesome-tiles/assets/10258162/036f8ff9-5936-4857-bd18-d1eb28a1c9b7)
