### ISSUE TITLE
Gap not between windows

### ISSUE THREAD

**Issue by Dolland** [velitasali/gnome-shell-extension-awesome-tiles#7]
Hi Veli!
I've noticed a thing that i suppose is an issue but i'm really not sure if it's intended:
if i set a gap for tiling, the gap is observed only on the external area of windows but not between windows, or at least is strangely performed.
I've put a screenshot of what i'm talking about to be clearer.

![immagine](https://user-images.githubusercontent.com/45694266/148236242-f66623b2-22c9-426f-a014-df6781352f05.png)

Is that a bug or is it correct?

**Comment by velitasali** [comment]
I experienced this issue on a Raspberry Pi running X11, and my guess is that windows don't exactly end up where the plugin tells them to.

The issue is not present on my main setup running Wayland, and I am unable to start the X11 session atm, so I will need to fix that first. 

Here is a screenshot from a Wayland session:
![Screenshot from 2022-01-05 21-27-01](https://user-images.githubusercontent.com/10258162/148269318-c27adb83-4ece-4546-8ffa-3b8af11b77a7.png)

**Comment by Dolland** [comment]
Uhm, so also on Wayland "Gap" doesn't apply to inner side of windows, that's what i though was a bug.
Is that correct that windows stay "connected" on inner sides?
I though that gap would act like that:
(manually resized and positioned)

![immagine](https://user-images.githubusercontent.com/45694266/148273345-afc454ba-59d2-480f-8dd1-685602335282.png)

**Comment by velitasali** [comment]
Yes, there should be no inner gaps. That is the expected behavior. I might add an option to add inner gaps later. 

Does the problem persist in the Wayland session?

**Comment by Dolland** [comment]
Oh, so my bad, i though it was a bug :D
Cannot try on Wayland by now but if by design there isn't inner gap (it would be usefull to add as optional) i think it's ok like is now

**Comment by velitasali** [comment]
> Oh, so my bad, i though it was a bug :D

No problem :) Those uneven spaces in the first screenshot are a bug. I will focus on that issue later. 

> Cannot try on Wayland by now but if by design there isn't inner gap (it would be usefull to add as optional) i think it's ok like is now

Yes, I agree. I will probably add it in the next release :)

**Comment by nergdron** [comment]
just trying out this extension today, and I'd really love it if there was an inner gap option that matches the outer gap. really looking forward to this feature.

**Comment by anjoweichbrodt** [comment]
Many thanks for the extension. It works great. An inner gap option would be awesome!

**Comment by velitasali** [comment]
Hi! Gaps between windows is now supported. Enabling it in the settings after the update should do it.
