### ISSUE TITLE
GTK apps reset their sizes on focus change

### ISSUE THREAD

**Issue by velitasali** [velitasali/gnome-shell-extension-awesome-tiles#9]
This is an upstream bug that appeared after an update to mutter. What happens is windows restore a previous size (set by `move_resize_frame`) after they lose focus. As this is an upstream issue, there is nothing that can be done here.

You can track the issue here: https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

**Comment by velitasali** [comment]
The change causing the issue has been reverted for mutter 41 here https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2293, meaning the issue will soon be gone there. 

For 42, GTK4 apps should start acting normally again, however, GTK3 patch remains unmerged.

**Comment by eboye** [comment]
Mutter 41.4-1 doesn't suffer from this. Just upgraded my Manjaro to it and works as intended.

**Comment by velitasali** [comment]
@eboye Thanks for the feedback :) I am on 42.beta and GTK4 apps are also alright, but GTK3 needs the related MR[^1] to be merged. Then, I can continue working on this project and make a release for 42. 

[^1]: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4390

**Comment by velitasali** [comment]
The remaining (GTK3) issue has been fixed on the mutter side, it should work out-of-the-box in GNOME 42 when it is released. 


The related commit: https://gitlab.gnome.org/GNOME/mutter/-/commit/251bb45ec0fdfd2f7f4ba4c89bdd74be66141035
